# Generated by Django 5.1.1 on 2025-11-02 16:27

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(help_text='Email: локальна частина 1–35, домен 3–35, без послідовних крапок', max_length=71, unique=True, validators=[users.models.validate_email_custom]),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(help_text='Прізвище: 1–50 символів, кирилиця/латиниця, дефіс (не на початку/кінці)', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message="Ім'я та прізвище: лише літери (кирилиця/латиниця), дефіс не на початку чи в кінці.", regex='^(?!-)[A-Za-zА-Яа-яїЇіІєЄґҐ]+(-[A-Za-zА-Яа-яїЇіІєЄґҐ]+)*(?<!-)$'), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text="Ім'я: 1–50 символів, кирилиця/латиниця, дефіс (не на початку/кінці)", max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message="Ім'я та прізвище: лише літери (кирилиця/латиниця), дефіс не на початку чи в кінці.", regex='^(?!-)[A-Za-zА-Яа-яїЇіІєЄґҐ]+(-[A-Za-zА-Яа-яїЇіІєЄґҐ]+)*(?<!-)$'), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
