# Generated by Django 5.1.1 on 2025-12-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_users_user_date_jo_064c8f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_privacy_at',
            field=models.DateTimeField(blank=True, help_text='Час згоди з політикою конфіденційності', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='agree_terms_at',
            field=models.DateTimeField(blank=True, help_text='Час згоди з умовами', null=True),
        ),
    ]
