FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y postgresql-client
COPY . .


RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*


ENV PYTHONUNBUFFERED=1
CMD ["sh", "entrypoint.sh"]