# /mnt/d/handmade_marketplace/backend/docker-compose.yml

services:
  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - REDIS_URL=${REDIS_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@marketplace_database:5432/${DB_DATABASE}
    volumes:
      - ./api_gateway:/app
    depends_on:
      marketplace_database:
        condition: service_healthy
      redis:
        condition: service_healthy
      user_service:  # Додай залежність від user_service
        condition: service_healthy
    networks:
      - handmade_network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  marketplace_database:
    # ... (без змін)

  db-extensions-init:
    # ... (без змін)

  redis:
    # ... (без змін)

  user_service:
    build:
      context: ./user_service  # Шлях до папки user_service
      dockerfile: Dockerfile
    container_name: user_service
    restart: unless-stopped
    ports:
      - "8001:8001"  # Порт для user_service
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - REDIS_URL=${REDIS_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@marketplace_database:5432/${DB_DATABASE}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}  # Якщо потрібно для email
    volumes:
      - ./user_service:/app
    depends_on:
      marketplace_database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - handmade_network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8001/users/health || exit 1"]  # Додай /health до user_service views.py, якщо потрібно (аналогічно до gateway)
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  marketplace_db_data:
  redis_data:

networks:
  handmade_network:
    driver: bridge