services:
  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile.local
    container_name: api-gateway-local
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    environment:
      - SECRET_KEY=${SECRET_KEY:-django-insecure-0gos56jbkua+tptfdw5j#(ipe%^%kwt2)ekc@$8!*9++o166wx}
      - DEBUG=False
      - REDIS_URL=redis://redis:6379/1
      - FRONTEND_URL=http://localhost:5173
      - USER_SERVICE_URL=http://user-service:8001
      - PRODUCT_SERVICE_URL=http://product-service:8002
      - ORDER_SERVICE_URL=http://order-service:8003
      - ALLOWED_HOSTS=localhost,127.0.0.1,user-service,product-service,order-service,api-gateway
      - DATABASE_URL=postgresql://dev:sysadmin@marketplace-database:5432/marketplace?options=-c%20search_path%3Dgateway_schema
      - ENV=local
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
      - TZ=Europe/Kiev
    volumes:
      - ./api_gateway/app:/app/app
      - ./api_gateway/manage.py:/app/manage.py
      - ./api_gateway/logs:/app/logs
    depends_on:
      marketplace-database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - handmade_network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://api-gateway:8000/health || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  marketplace-database:
    image: postgres:17-alpine
    container_name: marketplace-database-local
    restart: unless-stopped
    volumes:
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./infrastructure/postgres/init-extensions.sql:/docker-entrypoint-initdb.d/00-init-extensions.sql
      - marketplace_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: sysadmin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d marketplace"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - handmade_network

  redis:
    image: redis:7.4.0-alpine
    container_name: marketplace-redis-local
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - handmade_network

  user-service:
    build:
      context: ./user_service
      dockerfile: Dockerfile.local
    container_name: user-service-local
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - .env.local
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - DATABASE_URL=postgresql://dev:sysadmin@marketplace-database:5432/marketplace?options=-c%20search_path%3Dusers_schema
      - ALLOWED_HOSTS=localhost,127.0.0.1,user-service,product-service,order-service,api-gateway
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/1
      - ENV=local
      - USER_SERVICE_URL=http://user-service:8001
      - PRODUCT_SERVICE_URL=http://product-service:8002
      - ORDER_SERVICE_URL=http://order-service:8003
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
      - TZ=Europe/Kiev
    volumes:
      - ./user_service/user_service:/app/user_service
      - ./user_service/users:/app/users
      - ./user_service/manage.py:/app/manage.py
      - ./user_service/logs:/app/logs
    depends_on:
      marketplace-database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - handmade_network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://user-service:8001/health || exit 1"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 120s

  user-service-celery:
    build:
      context: ./user_service
      dockerfile: Dockerfile.local
    container_name: user-service-celery-local
    restart: unless-stopped
    command: sh ./entrypoint-celery.sh
    env_file:
      - .env.local
    environment:
      - SERVICE_TYPE=celery
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DATABASE_URL=postgresql://dev:sysadmin@marketplace-database:5432/marketplace?options=-c%20search_path%3Dusers_schema
      - ENV=local
      - CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP=True
      - TZ=Europe/Kiev
    depends_on:
      redis:
        condition: service_healthy
      marketplace-database:
        condition: service_healthy
    networks:
      - handmade_network

  product-service:
    build:
      context: ./product_service
      dockerfile: Dockerfile.local
    container_name: product-service-local
    restart: unless-stopped
    ports:
      - "8002:8002"
    env_file:
      - .env.local
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - DATABASE_URL=postgresql://dev:sysadmin@marketplace-database:5432/marketplace?options=-c%20search_path%3Dproducts_schema
      - ALLOWED_HOSTS=localhost,127.0.0.1,user-service,product-service,order-service,api-gateway
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/1
      - ENV=local
      - USER_SERVICE_URL=http://user-service:8001
      - PRODUCT_SERVICE_URL=http://product-service:8002
      - ORDER_SERVICE_URL=http://order-service:8003
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
      - TZ=Europe/Kiev
    volumes:
      - ./product_service/product_service:/app/product_service
      - ./product_service/products:/app/products
      - ./product_service/manage.py:/app/manage.py
      - ./product_service/logs:/app/logs
    depends_on:
      marketplace-database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - handmade_network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://product-service:8002/health || exit 1"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 120s

  product-service-celery:
    build:
      context: ./product_service
      dockerfile: Dockerfile.local
    container_name: product-service-celery-local
    restart: unless-stopped
    command: sh ./entrypoint-celery.sh
    env_file:
      - .env.local
    environment:
      - SERVICE_TYPE=celery
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DATABASE_URL=postgresql://dev:sysadmin@marketplace-database:5432/marketplace?options=-c%20search_path%3Dproducts_schema
      - ENV=local
      - CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP=True
      - TZ=Europe/Kiev
    depends_on:
      redis:
        condition: service_healthy
      marketplace-database:
        condition: service_healthy
    networks:
      - handmade_network

  order-service:
    build:
      context: ./order_service
      dockerfile: Dockerfile.local
    container_name: order-service-local
    restart: unless-stopped
    ports:
      - "8003:8003"
    env_file:
      - .env.local
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DATABASE_URL=postgresql://dev:sysadmin@marketplace-database:5432/marketplace?options=-c%20search_path%3Dorders_schema
      - ENV=local
      - USER_SERVICE_URL=http://user-service:8001
      - PRODUCT_SERVICE_URL=http://product-service:8002
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
      - TZ=Europe/Kiev
    volumes:
      - ./order_service/order_service:/app/order_service
      - ./order_service/orders:/app/orders
      - ./order_service/manage.py:/app/manage.py
      - ./order_service/logs:/app/logs
    depends_on:
      marketplace-database:
        condition: service_healthy
    networks:
      - handmade_network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://order-service:8003/health || exit 1"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 120s

  order-service-celery:
    build:
      context: ./order_service
      dockerfile: Dockerfile.local
    container_name: order-service-celery-local
    restart: unless-stopped
    command: sh ./entrypoint-celery.sh
    env_file:
      - .env.local
    environment:
      - SERVICE_TYPE=celery
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DATABASE_URL=postgresql://dev:sysadmin@marketplace-database:5432/marketplace?options=-c%20search_path%3Dorders_schema
      - ENV=local
      - CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP=True
      - TZ=Europe/Kiev
    depends_on:
      redis:
        condition: service_healthy
      marketplace-database:
        condition: service_healthy
    networks:
      - handmade_network

volumes:
  marketplace_db_data:
  redis_data:

networks:
  handmade_network:
    driver: bridge