#gateway
FROM python:3.12-slim

WORKDIR /app

# Встановлюємо postgresql-client + dos2unix + netcat
RUN apt-get update && \
    apt-get install -y postgresql-client dos2unix netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Фіксимо line endings
RUN find . -name "entrypoint*.sh" -exec dos2unix {} \; && \
    find . -name "entrypoint*.sh" -exec chmod +x {} \;

# Статичні файли (якщо є)
RUN python manage.py collectstatic --noinput || true

ENV PYTHONUNBUFFERED=1
CMD ["sh", "entrypoint.sh"]