FROM python:3.11-slim

# Встановлюємо postgresql-client + dos2unix + netcat
RUN apt-get update && \
    apt-get install -y postgresql-client dos2unix netcat-openbsd && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Фіксимо entrypoint.sh
RUN dos2unix entrypoint.sh && chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
